"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/ui/use-toast";
import { useAdminAuth } from "@/hooks/useAdminAuth";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Info, Calendar } from "lucide-react";
import { BRAND_PRESETS, BrandingPresetId } from "@/lib/brand-presets";
import { type MonthAvailability } from "@/components/ui/month-availability-calendar";
import { SchedulerAvailabilitySelector } from "@/components/scheduling/scheduler-availability-selector";
import { availabilityToSlots } from "@/lib/scheduling/availability-helpers";
import type { SlotDraft } from "@/lib/scheduling/availability-helpers";

export default function NewSchedulingRequestPage() {
  const router = useRouter();
  const { toast } = useToast();
  const { adminEmail } = useAdminAuth();
  const createRequest = useMutation(api.scheduling.createRequest);
  const settings = useQuery(api.settings.getAll) || {};

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [organizerEmail, setOrganizerEmail] = useState("");
  const [recipientEmails, setRecipientEmails] = useState("");
  const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC");
  const [durationMinutes, setDurationMinutes] = useState(60);
  const [maxSelectionsPerPerson, setMaxSelectionsPerPerson] = useState(1);
  // Branding
  const [brandingPreset, setBrandingPreset] = useState<BrandingPresetId>("ian");
  // Availability selection state
  const [selectedAvailability, setSelectedAvailability] = useState<MonthAvailability>({});
  const [enabledSlots, setEnabledSlots] = useState<Record<string, Set<string>>>({});
  // Work hours and availability from settings
  const workHoursStart = (settings.workHoursStart as string) || "09:00";
  const workHoursEnd = (settings.workHoursEnd as string) || "17:00";
  const workHoursDays = (settings.workHoursDays as string[]) || ["Mon", "Tue", "Wed", "Thu", "Fri"];
  const workHoursTimezone = (settings.workHoursTimezone as string) || Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
  const monthAvailability = (settings.schedulingAvailability as MonthAvailability) || {};
  const defaultSlotDurationMinutes = (settings.defaultSlotDurationMinutes as number) || 60;
  const defaultSlotIntervalMinutes = (settings.defaultSlotIntervalMinutes as number) || 60;

  // Handle slot toggle
  const handleSlotToggle = (date: string, slotStart: string) => {
    setEnabledSlots(prev => {
      const newEnabled = { ...prev };
      if (!newEnabled[date]) {
        newEnabled[date] = new Set<string>();
      }
      const dateSet = new Set(newEnabled[date]);
      if (dateSet.has(slotStart)) {
        dateSet.delete(slotStart);
      } else {
        dateSet.add(slotStart);
      }
      newEnabled[date] = dateSet;
      return newEnabled;
    });
  };

  // Initialize enabled slots when a day is selected
  useEffect(() => {
    setEnabledSlots(prev => {
      const newEnabledSlots: Record<string, Set<string>> = { ...prev };
      let hasChanges = false;
      
      Object.keys(selectedAvailability).forEach(date => {
        if (selectedAvailability[date]?.available && !newEnabledSlots[date]) {
          // Get active slots for this day
          const dayAvail = selectedAvailability[date];
          const slots: string[] = [];
          
          if (dayAvail.autoGeneratedSlots) {
            dayAvail.autoGeneratedSlots.forEach(slot => {
              if (!dayAvail.excludedSlots?.includes(slot.start)) {
                slots.push(slot.start);
              }
            });
          }
          
          if (dayAvail.specificSlots) {
            for (let i = 0; i < dayAvail.specificSlots.length; i += 2) {
              const start = dayAvail.specificSlots[i];
              if (start) slots.push(start);
            }
          }
          
          // Enable all slots by default
          if (slots.length > 0) {
            newEnabledSlots[date] = new Set(slots);
            hasChanges = true;
          }
        }
      });
      
      // Remove enabled slots for deselected days
      Object.keys(prev).forEach(date => {
        if (!selectedAvailability[date]?.available) {
          delete newEnabledSlots[date];
          hasChanges = true;
        }
      });
      
      return hasChanges ? newEnabledSlots : prev;
    });
  }, [selectedAvailability]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title || !organizerEmail) {
      toast({ title: "Missing info", description: "Title and organizer email are required", variant: "destructive" });
      return;
    }
    
    // Convert selected availability + enabled slots to slots
    const slots = availabilityToSlots(selectedAvailability, enabledSlots, durationMinutes);
    
    if (slots.length === 0) {
      toast({ title: "No slots", description: "Select at least one day and enable at least one time slot", variant: "destructive" });
      return;
    }
    
    const recipients = recipientEmails
      .split(",")
      .map((e) => e.trim())
      .filter((e) => e);
    
    // Convert slots to timestamp format
    const parsedSlots = slots
      .filter((s) => s.start && s.end)
      .map((s) => ({ start: new Date(s.start).getTime(), end: new Date(s.end).getTime() }))
      .filter((s) => s.end > s.start);
    
    if (parsedSlots.length === 0) {
      toast({ title: "No valid slots", description: "Please select valid time slots", variant: "destructive" });
      return;
    }

    try {
      const id = await createRequest({
        title,
        description: description || undefined,
        organizerEmail,
        recipientEmails: recipients,
        timezone,
        durationMinutes: Number(durationMinutes),
        maxSelectionsPerPerson: Number(maxSelectionsPerPerson) || 1,
        windowStart: parsedSlots.reduce((min, s) => Math.min(min, s.start), Infinity),
        windowEnd: parsedSlots.reduce((max, s) => Math.max(max, s.end), -Infinity),
        slots: parsedSlots,
        brandingPreset,
        email: adminEmail || undefined,
      });
      toast({ title: "Request created", description: "Share invite links from the request page" });
      router.push(`/admin/scheduling/${id}`);
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Failed to create request", variant: "destructive" });
    }
  };

  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 py-8 sm:py-12">
      <div className="mb-8 sm:mb-12">
        <Link href="/admin/scheduling" className="text-sm text-accent hover:text-accent/80 font-bold uppercase tracking-wider inline-flex items-center gap-1 group mb-4">
          <span className="group-hover:-translate-x-1 transition-transform">←</span>
          Back to Scheduling
        </Link>
        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black uppercase tracking-tight text-foreground mb-4" style={{ fontWeight: '900', letterSpacing: '-0.02em' }}>
          New Booking Request
        </h1>
        <p className="text-foreground/70 text-base sm:text-lg">
          Create a Calendly-style booking request to send to multiple people. First-come-first-served, no overlapping picks.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-8">
        {/* Info Banner */}
        <Card className="border border-accent/30 bg-accent/5">
          <CardContent className="p-4 sm:p-6">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 mt-0.5 text-accent flex-shrink-0" />
              <div className="text-sm text-foreground/80 leading-relaxed">
                <p className="font-black uppercase tracking-wider mb-3 text-foreground" style={{ fontWeight: '900' }}>
                  How this works:
                </p>
                <ol className="ml-4 list-decimal space-y-2">
                  <li>Enter booking details (title, organizer, recipients, duration)</li>
                  <li>Choose a branding preset for the public booking page</li>
                  <li>Add time slots using the generator or manual entry</li>
                  <li>Share invite links with recipients (or create shareable links)</li>
                  <li>Recipients select their preferred time slot (first-come-first-served)</li>
                </ol>
              </div>
            </div>
          </CardContent>
        </Card>
        {/* Step 1: Branding Preset */}
        <Card className="border border-foreground/20">
          <CardHeader className="pb-4">
            <CardTitle className="text-xl font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
              Step 1: Branding Preset
            </CardTitle>
            <CardDescription className="text-base">
              Choose a lightweight theme for the public booking page
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {[BRAND_PRESETS.ian, BRAND_PRESETS.styledriven, BRAND_PRESETS.voding].map((p) => {
                const isSelected = brandingPreset === p.id;
                const hexToRgba = (hex: string, alpha: number): string => {
                  const r = parseInt(hex.slice(1, 3), 16);
                  const g = parseInt(hex.slice(3, 5), 16);
                  const b = parseInt(hex.slice(5, 7), 16);
                  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
                };
                return (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => setBrandingPreset(p.id)}
                    className="rounded-lg border p-6 transition-colors flex items-center justify-center"
                    style={{ 
                      background: p.primary, 
                      color: p.text,
                      borderColor: isSelected ? p.accent : hexToRgba(p.text, 0.2),
                      borderWidth: '1px',
                      borderStyle: 'solid',
                      backgroundColor: isSelected ? hexToRgba(p.accent, 0.1) : p.primary
                    }}
                    onMouseEnter={(e) => {
                      if (!isSelected) {
                        e.currentTarget.style.borderColor = hexToRgba(p.accent, 0.5);
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!isSelected) {
                        e.currentTarget.style.borderColor = hexToRgba(p.text, 0.2);
                      }
                    }}
                  >
                    {p.logoUrl ? (
                      <Image
                        src={p.logoUrl}
                        alt={p.name}
                        width={160}
                        height={60}
                        className="h-12 w-auto object-contain opacity-90"
                        style={{ filter: 'brightness(0) invert(1)' }}
                      />
                    ) : (
                      <div className="text-sm uppercase font-bold tracking-wider opacity-80">{p.name}</div>
                    )}
                  </button>
                );
              })}
            </div>
          </CardContent>
        </Card>

        {/* Step 2: Booking Details */}
        <Card className="border border-foreground/20">
          <CardHeader className="pb-4">
            <CardTitle className="text-xl font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
              Step 2: Booking Details
            </CardTitle>
            <CardDescription className="text-base">
              Enter the basic information for this booking request
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
              <Label className="text-sm font-black uppercase tracking-wider mb-3 block" style={{ fontWeight: '900' }}>Title *</Label>
              <Input className="h-12 text-base" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="30-min intro call" required />
            </div>
            <div>
              <Label className="text-sm font-black uppercase tracking-wider mb-3 block" style={{ fontWeight: '900' }}>Description</Label>
              <Textarea className="text-base" rows={3} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Context, agenda, etc." />
            </div>
            <div>
              <Label className="text-sm font-black uppercase tracking-wider mb-3 block" style={{ fontWeight: '900' }}>Organizer Email *</Label>
              <Input className="h-12 text-base" type="email" value={organizerEmail} onChange={(e) => setOrganizerEmail(e.target.value)} placeholder="you@company.com" required />
            </div>
            <div>
              <Label className="text-sm font-black uppercase tracking-wider mb-3 block" style={{ fontWeight: '900' }}>Recipient Emails (comma-separated)</Label>
              <Textarea className="text-base" rows={2} value={recipientEmails} onChange={(e) => setRecipientEmails(e.target.value)} placeholder="a@example.com, b@example.com (optional)" />
              <p className="mt-2 text-xs text-foreground/60">Leave empty to create a booking request without recipients</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <Label className="text-sm font-black uppercase tracking-wider mb-3 block" style={{ fontWeight: '900' }}>Timezone</Label>
                <Input className="h-12 text-base" value={timezone} onChange={(e) => setTimezone(e.target.value)} placeholder="America/New_York" />
              </div>
              <div>
                <div className="flex items-center justify-between mb-3">
                  <Label className="text-sm font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>Duration (minutes) *</Label>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <button type="button" aria-label="What is duration?" className="text-foreground/60 hover:text-foreground">
                          <Info className="h-4 w-4" />
                        </button>
                      </TooltipTrigger>
                      <TooltipContent>
                        Length of each meeting. Generated slots use this to compute end times.
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
                <Input className="h-12 text-base" type="number" min={5} step={5} value={durationMinutes} onChange={(e) => setDurationMinutes(Number(e.target.value))} required />
              </div>
              <div>
                <div className="flex items-center justify-between mb-3">
                  <Label className="text-sm font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>Max Selections Per Person</Label>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <button type="button" aria-label="What is max selections?" className="text-foreground/60 hover:text-foreground">
                          <Info className="h-4 w-4" />
                        </button>
                      </TooltipTrigger>
                      <TooltipContent>
                        Maximum number of time slots each person can book. Default is 1.
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
                <Input className="h-12 text-base" type="number" min={1} step={1} value={maxSelectionsPerPerson} onChange={(e) => setMaxSelectionsPerPerson(Number(e.target.value))} required />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Step 3: Select Availability */}
        <Card className="border border-foreground/20">
          <CardHeader className="pb-4">
            <CardTitle className="text-xl font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
              Step 3: Select Availability
            </CardTitle>
            <CardDescription className="text-base">
              Select which days and time slots from your availability settings to offer for this scheduler. Configure availability in Settings → Availability tab.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {Object.keys(monthAvailability).length === 0 ? (
              <div className="p-6 border border-foreground/20 rounded-lg bg-foreground/5 text-center">
                <Calendar className="h-12 w-12 mx-auto mb-4 text-foreground/40" />
                <p className="text-sm text-foreground/60 mb-2">
                  No availability configured. Go to <strong>Settings → Availability</strong> to configure your available days and time slots.
                </p>
              </div>
            ) : (
              <SchedulerAvailabilitySelector
                availability={monthAvailability}
                selectedAvailability={selectedAvailability}
                onSelectionChange={setSelectedAvailability}
                enabledSlots={enabledSlots}
                onSlotToggle={handleSlotToggle}
                durationMinutes={durationMinutes}
                workHoursStart={workHoursStart}
                workHoursEnd={workHoursEnd}
                defaultSlotDurationMinutes={defaultSlotDurationMinutes}
                defaultSlotIntervalMinutes={defaultSlotIntervalMinutes}
              />
            )}
          </CardContent>
        </Card>

        {/* Submit */}
        <div className="flex flex-col sm:flex-row gap-4">
          <Button 
            type="submit" 
            className="w-full sm:flex-1 font-black uppercase tracking-wider hover:bg-accent/90 transition-colors"
            style={{ backgroundColor: '#FFA617', fontWeight: '900' }}
          >
            <Calendar className="mr-2 h-4 w-4" />
            Create Booking Request
          </Button>
          <Link href="/admin/scheduling" className="w-full sm:w-auto">
            <Button 
              type="button" 
              variant="outline"
              className="w-full sm:w-auto font-bold uppercase tracking-wider hover:bg-foreground/10 transition-colors"
            >
              Cancel
            </Button>
          </Link>
        </div>
      </form>
    </div>
  );
}


