"use client";

import { useState, useEffect } from "react";
import { ChevronLeft, ChevronRight, Calendar } from "lucide-react";
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameMonth, addMonths, subMonths, getDay, isToday } from "date-fns";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export type DayAvailability = {
  date: string; // yyyy-mm-dd
  available: boolean;
  wholeDay?: boolean;
  timeRanges?: Array<{ start: string; end: string }>; // HH:mm format
  specificSlots?: Array<{ start: string; end: string }>; // ISO datetime strings
  useWorkHours?: boolean;
  // Auto-generated slots based on work hours and duration
  autoGeneratedSlots?: Array<{ start: string; end: string }>; // ISO datetime strings
  excludedSlots?: Array<string>; // ISO datetime strings to exclude from auto-generated
};

export type MonthAvailability = {
  [date: string]: DayAvailability;
};

interface MonthAvailabilityCalendarProps {
  availability: MonthAvailability;
  onAvailabilityChange: (availability: MonthAvailability) => void;
  className?: string;
  minDate?: Date;
  maxDate?: Date;
  workHoursStart?: string; // HH:mm
  workHoursEnd?: string; // HH:mm
  durationMinutes?: number; // Duration for slot generation
  intervalMinutes?: number; // Interval between slots
}

// Helper function to generate slots for a day
function generateSlotsForDay(
  dateStr: string,
  startTime: string,
  endTime: string,
  durationMinutes: number,
  intervalMinutes: number
): Array<{ start: string; end: string }> {
  const slots: Array<{ start: string; end: string }> = [];
  const [startHour, startMin] = startTime.split(':').map(Number);
  const [endHour, endMin] = endTime.split(':').map(Number);
  
  const startDate = new Date(dateStr + "T00:00:00");
  startDate.setHours(startHour, startMin, 0, 0);
  
  const endDate = new Date(dateStr + "T00:00:00");
  endDate.setHours(endHour, endMin, 0, 0);
  
  let current = new Date(startDate);
  
  while (current.getTime() + durationMinutes * 60_000 <= endDate.getTime()) {
    const slotStart = new Date(current);
    const slotEnd = new Date(current.getTime() + durationMinutes * 60_000);
    
    slots.push({
      start: slotStart.toISOString(),
      end: slotEnd.toISOString(),
    });
    
    current = new Date(current.getTime() + intervalMinutes * 60_000);
  }
  
  return slots;
}

export function MonthAvailabilityCalendar({
  availability,
  onAvailabilityChange,
  className,
  minDate,
  maxDate,
  workHoursStart = "09:00",
  workHoursEnd = "17:00",
  durationMinutes = 60,
  intervalMinutes = 60,
}: MonthAvailabilityCalendarProps) {
  const [currentMonth, setCurrentMonth] = useState(new Date());

  const monthStart = startOfMonth(currentMonth);
  const monthEnd = endOfMonth(currentMonth);
  const daysInMonth = eachDayOfInterval({ start: monthStart, end: monthEnd });

  // Get first day of week (0 = Sunday, 1 = Monday, etc.)
  const firstDayOfWeek = getDay(monthStart);

  // Create calendar grid with empty cells for days before month start
  const calendarDays: (Date | null)[] = [];
  for (let i = 0; i < firstDayOfWeek; i++) {
    calendarDays.push(null);
  }
  daysInMonth.forEach((day) => {
    calendarDays.push(day);
  });

  const handleDayToggle = (date: Date) => {
    const dateStr = format(date, "yyyy-MM-dd");
    const current = availability[dateStr] || { date: dateStr, available: false };
    
    if (!current.available) {
      // Day is being marked as available - auto-generate slots
      const slots = generateSlotsForDay(
        dateStr,
        workHoursStart,
        workHoursEnd,
        durationMinutes,
        intervalMinutes
      );
      
      const updated = {
        ...availability,
        [dateStr]: {
          ...current,
          available: true,
          useWorkHours: true,
          autoGeneratedSlots: slots,
          excludedSlots: [],
        },
      };
      
      onAvailabilityChange(updated);
    } else {
      // Day is being marked as unavailable
      const updated = {
        ...availability,
        [dateStr]: {
          ...current,
          available: false,
        },
      };
      
      onAvailabilityChange(updated);
    }
  };

  const handlePrevMonth = () => {
    const prevMonth = subMonths(currentMonth, 1);
    // Don't allow going to past months if minDate is set
    if (minDate && prevMonth < startOfMonth(minDate)) {
      return;
    }
    setCurrentMonth(prevMonth);
  };

  const handleNextMonth = () => {
    setCurrentMonth(addMonths(currentMonth, 1));
  };

  const isDateDisabled = (date: Date) => {
    if (minDate && date < minDate) return true;
    if (maxDate && date > maxDate) return true;
    return false;
  };

  const weekDays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

  return (
    <div className={cn("w-full", className)}>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={handlePrevMonth}
          disabled={minDate ? startOfMonth(currentMonth) <= startOfMonth(minDate) : false}
          className="h-8 w-8 p-0 hover:bg-accent/10 disabled:opacity-30 disabled:cursor-not-allowed"
        >
          <ChevronLeft className="h-4 w-4" />
        </Button>
        <div className="flex items-center gap-2">
          <Calendar className="h-5 w-5 text-accent" />
          <div className="text-lg font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
            {format(currentMonth, "MMMM yyyy")}
          </div>
        </div>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={handleNextMonth}
          className="h-8 w-8 p-0 hover:bg-accent/10"
        >
          <ChevronRight className="h-4 w-4" />
        </Button>
      </div>

      {/* Week day headers */}
      <div className="grid grid-cols-7 gap-2 mb-2">
        {weekDays.map((day) => (
          <div
            key={day}
            className="text-xs font-black uppercase tracking-wider text-center text-foreground/60 py-2"
            style={{ fontWeight: '900' }}
          >
            {day}
          </div>
        ))}
      </div>

      {/* Calendar grid */}
      <div className="grid grid-cols-7 gap-2">
        {calendarDays.map((date, idx) => {
          if (!date) {
            return <div key={idx} className="h-12" />;
          }

          const dateStr = format(date, "yyyy-MM-dd");
          const dayAvailability = availability[dateStr];
          const isAvailable = dayAvailability?.available || false;
          const isDisabled = isDateDisabled(date);
          const isCurrentMonth = isSameMonth(date, currentMonth);
          const isCurrentDay = isToday(date);

          return (
            <button
              key={date.toISOString()}
              type="button"
              onClick={() => !isDisabled && handleDayToggle(date)}
              disabled={isDisabled}
              className={cn(
                "h-12 rounded border text-sm font-black uppercase tracking-wider transition-all duration-200 relative",
                !isCurrentMonth && "opacity-30",
                isDisabled && "opacity-20 cursor-not-allowed",
                !isDisabled && !isAvailable && "border-foreground/20 hover:border-foreground/40 hover:bg-foreground/5 text-foreground/60",
                !isDisabled && isAvailable && "border-accent bg-accent/20 text-accent hover:bg-accent/30 hover:border-accent/80",
                isCurrentDay && "ring-2 ring-accent/50",
              )}
              style={{ fontWeight: '900' }}
            >
              {format(date, "d")}
              {isAvailable && (
                <div className="absolute bottom-1 left-1/2 -translate-x-1/2 w-1 h-1 rounded-full bg-accent" />
              )}
            </button>
          );
        })}
      </div>

      {/* Legend */}
      <div className="mt-4 flex items-center justify-center gap-4 text-xs text-foreground/60">
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded border border-foreground/20 bg-transparent" />
          <span>Unavailable</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded border border-accent bg-accent/20" />
          <span>Available</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded border-2 border-accent/50 ring-2 ring-accent/30" />
          <span>Today</span>
        </div>
      </div>
    </div>
  );
}

