"use client";

import { useState, useMemo, useEffect } from "react";
import { X, Plus, Clock, Calendar } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CustomTimePicker } from "@/components/ui/custom-time-picker";
import { CustomDatePicker } from "@/components/ui/custom-date-picker";
import { format } from "date-fns";
import type { DayAvailability } from "@/components/ui/month-availability-calendar";

interface DayConfigPanelProps {
  date: string; // yyyy-mm-dd
  availability: DayAvailability;
  onUpdate: (availability: DayAvailability) => void;
  workHoursStart?: string; // HH:mm
  workHoursEnd?: string; // HH:mm
  durationMinutes?: number; // Duration for slot generation
  intervalMinutes?: number; // Interval between slots
}

export function DayConfigPanel({
  date,
  availability,
  onUpdate,
  workHoursStart = "09:00",
  workHoursEnd = "17:00",
  durationMinutes = 60,
  intervalMinutes = 60,
}: DayConfigPanelProps) {
  const [showPanel, setShowPanel] = useState(true); // Show by default
  const [showOverrides, setShowOverrides] = useState(false);

  // Auto-generate slots if day is available but has no auto-generated slots
  useEffect(() => {
    if (availability.available && !availability.autoGeneratedSlots && availability.useWorkHours !== false) {
      // Generate slots for this day
      const slots: Array<{ start: string; end: string }> = [];
      const [startHour, startMin] = workHoursStart.split(':').map(Number);
      const [endHour, endMin] = workHoursEnd.split(':').map(Number);
      
      const startDate = new Date(date + "T00:00:00");
      startDate.setHours(startHour, startMin, 0, 0);
      
      const endDate = new Date(date + "T00:00:00");
      endDate.setHours(endHour, endMin, 0, 0);
      
      let current = new Date(startDate);
      
      while (current.getTime() + durationMinutes * 60_000 <= endDate.getTime()) {
        const slotStart = new Date(current);
        const slotEnd = new Date(current.getTime() + durationMinutes * 60_000);
        
        slots.push({
          start: slotStart.toISOString(),
          end: slotEnd.toISOString(),
        });
        
        current = new Date(current.getTime() + intervalMinutes * 60_000);
      }
      
      if (slots.length > 0) {
        onUpdate({
          ...availability,
          useWorkHours: true,
          autoGeneratedSlots: slots,
          excludedSlots: [],
        });
      }
    }
  }, [date, availability, workHoursStart, workHoursEnd, durationMinutes, intervalMinutes, onUpdate]);

  // Get active slots (auto-generated minus excluded, plus custom)
  const activeSlots = useMemo(() => {
    const slots: Array<{ start: string; end: string; type: 'auto' | 'custom' }> = [];
    
    // Add auto-generated slots (excluding excluded ones)
    if (availability.autoGeneratedSlots) {
      availability.autoGeneratedSlots.forEach(slot => {
        if (!availability.excludedSlots?.includes(slot.start)) {
          slots.push({ ...slot, type: 'auto' });
        }
      });
    }
    
    // Add custom specific slots
    if (availability.specificSlots) {
      for (let i = 0; i < availability.specificSlots.length; i += 2) {
        const start = availability.specificSlots[i];
        const end = availability.specificSlots[i + 1];
        if (start && end) {
          slots.push({ start, end, type: 'custom' });
        }
      }
    }
    
    return slots.sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime());
  }, [availability]);

  const toggleSlotExclusion = (slotStart: string) => {
    const excluded = availability.excludedSlots || [];
    const isExcluded = excluded.includes(slotStart);
    
    onUpdate({
      ...availability,
      excludedSlots: isExcluded
        ? excluded.filter(s => s !== slotStart)
        : [...excluded, slotStart],
    });
  };

  const formatTime = (isoString: string) => {
    return format(new Date(isoString), "h:mm a");
  };

  const addTimeRange = () => {
    const ranges = availability.timeRanges || [];
    onUpdate({
      ...availability,
      timeRanges: [...ranges, { start: workHoursStart, end: workHoursEnd }],
    });
  };

  const updateTimeRange = (index: number, key: "start" | "end", value: string) => {
    const ranges = [...(availability.timeRanges || [])];
    ranges[index] = { ...ranges[index], [key]: value };
    onUpdate({
      ...availability,
      timeRanges: ranges,
    });
  };

  const removeTimeRange = (index: number) => {
    const ranges = [...(availability.timeRanges || [])];
    ranges.splice(index, 1);
    onUpdate({
      ...availability,
      timeRanges: ranges,
    });
  };

  const addSpecificSlot = () => {
    const slots = availability.specificSlots || [];
    const startDate = date;
    const startTime = workHoursStart;
    const endTime = format(new Date(new Date(`${date}T${startTime}:00`).getTime() + (durationMinutes || 60) * 60_000), "HH:mm");
    
    onUpdate({
      ...availability,
      specificSlots: [
        ...slots,
        `${startDate}T${startTime}:00`,
        `${startDate}T${endTime}:00`,
      ],
    });
  };

  const updateSpecificSlot = (index: number, key: "start" | "end", value: string) => {
    const slots = [...(availability.specificSlots || [])];
    const slotIndex = key === "start" ? index * 2 : index * 2 + 1;
    if (slots[slotIndex]) {
      if (value.includes("T")) {
        slots[slotIndex] = value;
      } else {
        const existingSlot = new Date(slots[slotIndex]);
        const timeStr = format(existingSlot, "HH:mm");
        slots[slotIndex] = `${value}T${timeStr}:00`;
      }
    } else {
      if (value.includes("T")) {
        slots[slotIndex] = value;
      } else {
        slots[slotIndex] = `${value}T09:00:00`;
      }
    }
    onUpdate({
      ...availability,
      specificSlots: slots,
    });
  };

  const removeSpecificSlot = (index: number) => {
    const slots = [...(availability.specificSlots || [])];
    slots.splice(index * 2, 2);
    onUpdate({
      ...availability,
      specificSlots: slots,
    });
  };

  if (!availability.available) {
    return null;
  }

  return (
    <Card className="border border-foreground/20 mb-4">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Calendar className="h-4 w-4 text-accent" />
            <CardTitle className="text-base font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
              {format(new Date(date + "T00:00:00"), "MMM dd, yyyy")}
            </CardTitle>
            {activeSlots.length > 0 && (
              <span className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded-full bg-accent/20 text-accent border border-accent/30">
                {activeSlots.length} slot{activeSlots.length !== 1 ? 's' : ''}
              </span>
            )}
          </div>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => setShowPanel(!showPanel)}
            className="h-8 w-8 p-0"
          >
            {showPanel ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}
          </Button>
        </div>
      </CardHeader>
      {showPanel && (
        <CardContent className="space-y-4">
          {/* Auto-Generated Slots Display */}
          {availability.autoGeneratedSlots && availability.autoGeneratedSlots.length > 0 ? (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <Label className="text-sm font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                  Available Time Slots ({activeSlots.filter(s => s.type === 'auto').length} of {availability.autoGeneratedSlots.length})
                </Label>
                <span className="text-xs text-foreground/60">
                  Click to exclude/include slots
                </span>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                {availability.autoGeneratedSlots.map((slot, index) => {
                  const isExcluded = availability.excludedSlots?.includes(slot.start) || false;
                  return (
                    <button
                      key={index}
                      type="button"
                      onClick={() => toggleSlotExclusion(slot.start)}
                      className={`p-3 rounded-lg border-2 transition-all text-left ${
                        isExcluded
                          ? 'border-foreground/20 bg-foreground/5 opacity-50 line-through'
                          : 'border-accent/40 bg-accent/10 hover:border-accent/60 hover:bg-accent/20'
                      }`}
                    >
                      <div className="text-sm font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                        {formatTime(slot.start)} - {formatTime(slot.end)}
                      </div>
                      <div className="text-xs text-foreground/60 mt-1">
                        {isExcluded ? 'Excluded' : 'Available'}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          ) : (
            <div className="p-4 rounded-lg border border-foreground/20 bg-foreground/5 text-center">
              <Clock className="h-6 w-6 mx-auto mb-2 text-foreground/40" />
              <p className="text-sm text-foreground/60">
                Slots will be auto-generated based on your work hours ({workHoursStart} - {workHoursEnd}) and duration ({durationMinutes} min).
              </p>
            </div>
          )}

          {/* Override Options */}
          <div className="border-t border-foreground/10 pt-4">
            <div className="flex items-center justify-between mb-3">
              <Label className="text-sm font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                Override Options
              </Label>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setShowOverrides(!showOverrides)}
                className="h-8 text-xs font-black uppercase tracking-wider"
                style={{ fontWeight: '900' }}
              >
                {showOverrides ? 'Hide' : 'Show'} Overrides
              </Button>
            </div>
            
            {showOverrides && (
              <div className="space-y-4">
                {/* Custom Time Ranges */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label className="text-xs font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                      Custom Time Ranges
                    </Label>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={addTimeRange}
                      className="h-8 text-xs font-black uppercase tracking-wider"
                      style={{ fontWeight: '900' }}
                    >
                      <Plus className="h-3 w-3 mr-1" />
                      Add Range
                    </Button>
                  </div>
                  {(availability.timeRanges || []).map((range, index) => (
                    <div key={index} className="flex items-center gap-2 p-3 rounded-lg border border-foreground/10 bg-foreground/5">
                      <div className="flex-1 grid grid-cols-2 gap-2">
                        <div>
                          <Label className="text-xs font-black uppercase tracking-wider mb-1 block" style={{ fontWeight: '900' }}>
                            Start
                          </Label>
                          <CustomTimePicker
                            value={range.start}
                            onChange={(value) => updateTimeRange(index, "start", value)}
                            placeholder="Start time"
                          />
                        </div>
                        <div>
                          <Label className="text-xs font-black uppercase tracking-wider mb-1 block" style={{ fontWeight: '900' }}>
                            End
                          </Label>
                          <CustomTimePicker
                            value={range.end}
                            onChange={(value) => updateTimeRange(index, "end", value)}
                            placeholder="End time"
                          />
                        </div>
                      </div>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        onClick={() => removeTimeRange(index)}
                        className="h-8 w-8 p-0 text-destructive hover:text-destructive hover:bg-destructive/10"
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                </div>

                {/* Custom Specific Slots */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label className="text-xs font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                      Custom Specific Slots
                    </Label>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={addSpecificSlot}
                      className="h-8 text-xs font-black uppercase tracking-wider"
                      style={{ fontWeight: '900' }}
                    >
                      <Plus className="h-3 w-3 mr-1" />
                      Add Slot
                    </Button>
                  </div>
                  {(availability.specificSlots || []).length > 0 && (
                    <div className="space-y-2">
                      {Array.from({ length: (availability.specificSlots?.length || 0) / 2 }).map((_, index) => {
                        const startSlot = availability.specificSlots?.[index * 2];
                        const endSlot = availability.specificSlots?.[index * 2 + 1];
                        const startDate = startSlot ? format(new Date(startSlot), "yyyy-MM-dd") : date;
                        const startTime = startSlot ? format(new Date(startSlot), "HH:mm") : "09:00";
                        const endDate = endSlot ? format(new Date(endSlot), "yyyy-MM-dd") : date;
                        const endTime = endSlot ? format(new Date(endSlot), "HH:mm") : "10:00";

                        return (
                          <div key={index} className="p-3 rounded-lg border border-foreground/10 bg-foreground/5">
                            <div className="flex items-center justify-between mb-2">
                              <Label className="text-xs font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                                Slot {index + 1}
                              </Label>
                              <Button
                                type="button"
                                variant="ghost"
                                size="sm"
                                onClick={() => removeSpecificSlot(index)}
                                className="h-6 w-6 p-0 text-destructive hover:text-destructive hover:bg-destructive/10"
                              >
                                <X className="h-3 w-3" />
                              </Button>
                            </div>
                            <div className="grid grid-cols-2 gap-2">
                              <div>
                                <Label className="text-xs font-black uppercase tracking-wider mb-1 block" style={{ fontWeight: '900' }}>
                                  Start Date
                                </Label>
                                <CustomDatePicker
                                  value={startDate}
                                  onChange={(value) => updateSpecificSlot(index, "start", `${value}T${startTime}:00`)}
                                  placeholder="Start date"
                                />
                              </div>
                              <div>
                                <Label className="text-xs font-black uppercase tracking-wider mb-1 block" style={{ fontWeight: '900' }}>
                                  Start Time
                                </Label>
                                <CustomTimePicker
                                  value={startTime}
                                  onChange={(value) => updateSpecificSlot(index, "start", `${startDate}T${value}:00`)}
                                  placeholder="Start time"
                                />
                              </div>
                              <div>
                                <Label className="text-xs font-black uppercase tracking-wider mb-1 block" style={{ fontWeight: '900' }}>
                                  End Date
                                </Label>
                                <CustomDatePicker
                                  value={endDate}
                                  onChange={(value) => updateSpecificSlot(index, "end", `${value}T${endTime}:00`)}
                                  placeholder="End date"
                                />
                              </div>
                              <div>
                                <Label className="text-xs font-black uppercase tracking-wider mb-1 block" style={{ fontWeight: '900' }}>
                                  End Time
                                </Label>
                                <CustomTimePicker
                                  value={endTime}
                                  onChange={(value) => updateSpecificSlot(index, "end", `${endDate}T${value}:00`)}
                                  placeholder="End time"
                                />
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </CardContent>
      )}
    </Card>
  );
}
