"use client";

import { useState, useMemo, useEffect } from "react";
import { Calendar, ChevronDown, ChevronUp, Clock, CheckCircle2, X } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { MonthAvailabilityCalendar, type MonthAvailability, type DayAvailability } from "@/components/ui/month-availability-calendar";
import { format, startOfWeek, endOfWeek, eachDayOfInterval, startOfMonth, endOfMonth } from "date-fns";
import { cn } from "@/lib/utils";

interface SchedulerAvailabilitySelectorProps {
  availability: MonthAvailability; // Full availability from settings
  selectedAvailability: MonthAvailability; // Currently selected days for this scheduler
  onSelectionChange: (availability: MonthAvailability) => void;
  enabledSlots: Record<string, Set<string>>; // Which slots are enabled per day (date -> Set of slot start ISO strings)
  onSlotToggle: (date: string, slotStart: string) => void;
  durationMinutes: number;
  workHoursStart: string;
  workHoursEnd: string;
  defaultSlotDurationMinutes?: number;
  defaultSlotIntervalMinutes?: number;
}

export function SchedulerAvailabilitySelector({
  availability,
  selectedAvailability,
  onSelectionChange,
  enabledSlots,
  onSlotToggle,
  durationMinutes,
  workHoursStart,
  workHoursEnd,
  defaultSlotDurationMinutes = 60,
  defaultSlotIntervalMinutes = 60,
}: SchedulerAvailabilitySelectorProps) {
  const [expandedMonths, setExpandedMonths] = useState<Set<string>>(new Set());
  const [expandedDates, setExpandedDates] = useState<Set<string>>(new Set());

  // Get active slots for a day (auto-generated minus excluded, plus custom)
  const getActiveSlots = (dayAvail: DayAvailability): Array<{ start: string; end: string; type: 'auto' | 'custom' }> => {
    const slots: Array<{ start: string; end: string; type: 'auto' | 'custom' }> = [];
    
    // Add auto-generated slots (excluding excluded ones)
    if (dayAvail.autoGeneratedSlots) {
      dayAvail.autoGeneratedSlots.forEach(slot => {
        if (!dayAvail.excludedSlots?.includes(slot.start)) {
          slots.push({ ...slot, type: 'auto' });
        }
      });
    }
    
    // Add custom specific slots
    if (dayAvail.specificSlots) {
      for (let i = 0; i < dayAvail.specificSlots.length; i += 2) {
        const start = dayAvail.specificSlots[i];
        const end = dayAvail.specificSlots[i + 1];
        if (start && end) {
          slots.push({ start, end, type: 'custom' });
        }
      }
    }
    
    return slots.sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime());
  };

  // Handle day selection toggle
  const handleDayToggle = (date: Date) => {
    const dateStr = format(date, "yyyy-MM-dd");
    const dayAvail = availability[dateStr];
    
    if (!dayAvail || !dayAvail.available) {
      // Day is not available in settings, can't select
      return;
    }
    
    const isSelected = selectedAvailability[dateStr]?.available || false;
    const newSelection = { ...selectedAvailability };
    
    if (isSelected) {
      // Deselect day
      delete newSelection[dateStr];
    } else {
      // Select day - copy from availability
      newSelection[dateStr] = { ...dayAvail };
    }
    
    onSelectionChange(newSelection);
  };

  // Handle month deselection
  const handleDeselectMonth = (monthKey: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const newSelection = { ...selectedAvailability };
    const dates = selectedDatesByMonth[monthKey] || [];
    dates.forEach(date => {
      delete newSelection[date];
    });
    onSelectionChange(newSelection);
  };

  // Handle week deselection
  const handleDeselectWeek = (weekStart: Date, e: React.MouseEvent) => {
    e.stopPropagation();
    const weekEnd = endOfWeek(weekStart);
    const weekDays = eachDayOfInterval({ start: weekStart, end: weekEnd });
    const newSelection = { ...selectedAvailability };
    weekDays.forEach(day => {
      const dateStr = format(day, "yyyy-MM-dd");
      if (selectedAvailability[dateStr]?.available) {
        delete newSelection[dateStr];
      }
    });
    onSelectionChange(newSelection);
  };

  // Handle day deselection
  const handleDeselectDay = (date: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const newSelection = { ...selectedAvailability };
    delete newSelection[date];
    onSelectionChange(newSelection);
  };

  // Get selected dates grouped by month
  const selectedDatesByMonth = useMemo(() => {
    const byMonth: Record<string, string[]> = {};
    Object.keys(selectedAvailability)
      .filter(date => selectedAvailability[date]?.available)
      .sort()
      .forEach(date => {
        const monthKey = date.substring(0, 7); // yyyy-mm
        if (!byMonth[monthKey]) {
          byMonth[monthKey] = [];
        }
        byMonth[monthKey].push(date);
      });
    return byMonth;
  }, [selectedAvailability]);

  // Auto-expand first month
  useEffect(() => {
    if (expandedMonths.size === 0 && Object.keys(selectedDatesByMonth).length > 0) {
      const firstMonth = Object.keys(selectedDatesByMonth).sort()[0];
      setExpandedMonths(new Set([firstMonth]));
    }
  }, [selectedDatesByMonth, expandedMonths.size]);

  // Custom calendar that shows selection state
  const CustomCalendar = () => {
    const [currentMonth, setCurrentMonth] = useState(new Date());
    const monthStart = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), 1);
    const monthEnd = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 0);
    const daysInMonth = [];
    for (let d = new Date(monthStart); d <= monthEnd; d.setDate(d.getDate() + 1)) {
      daysInMonth.push(new Date(d));
    }

    const firstDayOfWeek = monthStart.getDay();
    const calendarDays: (Date | null)[] = [];
    for (let i = 0; i < firstDayOfWeek; i++) {
      calendarDays.push(null);
    }
    daysInMonth.forEach(day => calendarDays.push(day));

    const handlePrevMonth = () => {
      setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1, 1));
    };

    const handleNextMonth = () => {
      setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 1));
    };

    const isDayAvailable = (date: Date) => {
      const dateStr = format(date, "yyyy-MM-dd");
      return availability[dateStr]?.available || false;
    };

    const isDaySelected = (date: Date) => {
      const dateStr = format(date, "yyyy-MM-dd");
      return selectedAvailability[dateStr]?.available || false;
    };

    const weekDays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

    return (
      <div className="w-full">
        <div className="flex items-center justify-between mb-4">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={handlePrevMonth}
            className="h-8 w-8 p-0"
          >
            <ChevronDown className="h-4 w-4 rotate-90" />
          </Button>
          <div className="flex items-center gap-2">
            <Calendar className="h-5 w-5 text-accent" />
            <span className="text-lg font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
              {format(currentMonth, "MMMM yyyy")}
            </span>
          </div>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={handleNextMonth}
            className="h-8 w-8 p-0"
          >
            <ChevronDown className="h-4 w-4 -rotate-90" />
          </Button>
        </div>
        <div className="grid grid-cols-7 gap-1 mb-2">
          {weekDays.map(day => (
            <div key={day} className="text-center text-xs font-bold uppercase tracking-wider text-foreground/60 py-2">
              {day}
            </div>
          ))}
        </div>
        <div className="grid grid-cols-7 gap-1">
          {calendarDays.map((day, idx) => {
            if (!day) {
              return <div key={idx} className="aspect-square" />;
            }
            const dateStr = format(day, "yyyy-MM-dd");
            const isAvailable = isDayAvailable(day);
            const isSelected = isDaySelected(day);
            const isToday = format(day, "yyyy-MM-dd") === format(new Date(), "yyyy-MM-dd");
            const isPast = day < new Date() && !isToday;

            return (
              <button
                key={dateStr}
                type="button"
                onClick={() => isAvailable && !isPast && handleDayToggle(day)}
                disabled={!isAvailable || isPast}
                className={cn(
                  "aspect-square rounded-lg border-2 transition-all text-sm font-bold uppercase tracking-wider relative",
                  isPast && "opacity-30 cursor-not-allowed",
                  !isAvailable && !isPast && "border-foreground/20 bg-foreground/5 text-foreground/40 cursor-not-allowed",
                  isAvailable && !isSelected && !isPast && "border-foreground/30 bg-foreground/10 text-foreground/70 hover:border-accent/50 hover:bg-accent/10 cursor-pointer",
                  isSelected && "border-accent bg-accent text-background",
                  isToday && !isSelected && "ring-2 ring-accent/50"
                )}
              >
                {format(day, "d")}
                {isSelected && (
                  <div className="absolute -top-1 -right-1">
                    <div className="rounded-full bg-background p-0.5">
                      <CheckCircle2 className="h-3 w-3 text-accent" />
                    </div>
                  </div>
                )}
              </button>
            );
          })}
        </div>
      </div>
    );
  };

  const monthKeys = Object.keys(selectedDatesByMonth).sort();

  // Handle select all available days
  const handleSelectAll = () => {
    const newSelection: MonthAvailability = {};
    Object.keys(availability).forEach(date => {
      const dayAvail = availability[date];
      if (dayAvail?.available) {
        newSelection[date] = { ...dayAvail };
      }
    });
    onSelectionChange(newSelection);
  };

  // Handle deselect all
  const handleDeselectAll = () => {
    onSelectionChange({});
  };

  const availableDaysCount = Object.keys(availability).filter(date => availability[date]?.available).length;
  const selectedDaysCount = Object.keys(selectedAvailability).filter(date => selectedAvailability[date]?.available).length;

  return (
    <div className="space-y-6">
      {/* Calendar for selecting days */}
      <div className="border border-foreground/20 rounded-lg p-4 bg-foreground/5">
        <div className="flex items-center justify-between mb-4">
          <Label className="text-sm font-black uppercase tracking-wider block" style={{ fontWeight: '900' }}>
            Select Available Days
          </Label>
          <div className="flex items-center gap-2">
            {selectedDaysCount < availableDaysCount ? (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleSelectAll}
                className="h-8 px-3 text-xs font-bold uppercase tracking-wider"
              >
                Select All ({availableDaysCount})
              </Button>
            ) : (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleDeselectAll}
                className="h-8 px-3 text-xs font-bold uppercase tracking-wider text-red-500 hover:text-red-600 hover:bg-red-500/10"
              >
                Deselect All
              </Button>
            )}
          </div>
        </div>
        <CustomCalendar />
        <div className="mt-4 flex flex-wrap gap-4 text-xs text-foreground/60">
          <div className="flex items-center gap-2">
            <div className="w-4 h-4 rounded border-2 border-foreground/20 bg-foreground/5" />
            <span>Not Available</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-4 h-4 rounded border-2 border-foreground/30 bg-foreground/10" />
            <span>Available (Click to Select)</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-4 h-4 rounded border-2 border-accent bg-accent" />
            <span>Selected for This Scheduler</span>
          </div>
        </div>
      </div>

      {/* Selected Days with Time Slots - Grouped by Month */}
      {monthKeys.length > 0 ? (
        <div className="space-y-3">
          <Label className="text-sm font-black uppercase tracking-wider block" style={{ fontWeight: '900' }}>
            Selected Days ({Object.keys(selectedAvailability).filter(d => selectedAvailability[d]?.available).length})
          </Label>
          {monthKeys.map((monthKey) => {
            const dates = selectedDatesByMonth[monthKey];
            const [year, month] = monthKey.split('-').map(Number);
            const monthDate = new Date(year, month - 1, 1);
            const monthName = monthDate.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
            const isMonthExpanded = expandedMonths.has(monthKey);

            return (
              <Card key={monthKey} className="border border-foreground/20">
                <CardHeader
                  className="pb-3 cursor-pointer hover:bg-foreground/5 transition-colors"
                  onClick={() => {
                    const newExpanded = new Set(expandedMonths);
                    if (isMonthExpanded) {
                      newExpanded.delete(monthKey);
                    } else {
                      newExpanded.add(monthKey);
                    }
                    setExpandedMonths(newExpanded);
                  }}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {isMonthExpanded ? (
                        <ChevronUp className="h-5 w-5 text-accent" />
                      ) : (
                        <ChevronDown className="h-5 w-5 text-foreground/60" />
                      )}
                      <CardTitle className="text-lg font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                        {monthName}
                      </CardTitle>
                      <span className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded-full bg-accent/20 text-accent border border-accent/30">
                        {dates.length} day{dates.length !== 1 ? 's' : ''}
                      </span>
                    </div>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={(e) => handleDeselectMonth(monthKey, e)}
                      className="h-8 px-3 text-xs font-bold uppercase tracking-wider text-red-500 hover:text-red-600 hover:bg-red-500/10"
                    >
                      <X className="h-3 w-3 mr-1" />
                      Deselect Month
                    </Button>
                  </div>
                </CardHeader>
                {isMonthExpanded && (() => {
                  // Group dates by week
                  const datesByWeek: Record<string, string[]> = {};
                  dates.forEach(date => {
                    const dateObj = new Date(date + "T00:00:00");
                    const weekStart = startOfWeek(dateObj);
                    const weekKey = format(weekStart, "yyyy-MM-dd");
                    if (!datesByWeek[weekKey]) {
                      datesByWeek[weekKey] = [];
                    }
                    datesByWeek[weekKey].push(date);
                  });

                  const weekKeys = Object.keys(datesByWeek).sort();

                  return (
                    <CardContent className="pt-0 space-y-4">
                      {weekKeys.map((weekKey) => {
                        const weekDates = datesByWeek[weekKey];
                        const weekStart = new Date(weekKey + "T00:00:00");
                        const weekEnd = endOfWeek(weekStart);
                        const weekLabel = `${format(weekStart, "MMM d")} - ${format(weekEnd, "MMM d")}`;

                        return (
                          <div key={weekKey} className="space-y-2">
                            <div className="flex items-center justify-between pb-2 border-b border-foreground/10">
                              <span className="text-xs font-black uppercase tracking-wider text-foreground/70" style={{ fontWeight: '900' }}>
                                Week: {weekLabel}
                              </span>
                              <Button
                                type="button"
                                variant="ghost"
                                size="sm"
                                onClick={(e) => handleDeselectWeek(weekStart, e)}
                                className="h-7 px-2 text-xs font-bold uppercase tracking-wider text-red-500 hover:text-red-600 hover:bg-red-500/10"
                              >
                                <X className="h-3 w-3 mr-1" />
                                Deselect Week
                              </Button>
                            </div>
                            <div className="space-y-2">
                              {weekDates.map((date) => {
                                const dayAvail = selectedAvailability[date] || availability[date];
                                const slots = getActiveSlots(dayAvail);
                                const isDateExpanded = expandedDates.has(date);
                                const enabledSlotsForDay = enabledSlots[date] || new Set<string>();
                                const enabledCount = slots.filter(s => enabledSlotsForDay.has(s.start)).length;

                                return (
                                  <div key={date} className="border border-foreground/10 rounded-lg bg-foreground/5">
                                    <div
                                      className="p-3 cursor-pointer hover:bg-foreground/10 transition-colors flex items-center justify-between"
                                      onClick={() => {
                                        const newExpanded = new Set(expandedDates);
                                        if (isDateExpanded) {
                                          newExpanded.delete(date);
                                        } else {
                                          newExpanded.add(date);
                                        }
                                        setExpandedDates(newExpanded);
                                      }}
                                    >
                                      <div className="flex items-center gap-3">
                                        {isDateExpanded ? (
                                          <ChevronUp className="h-4 w-4 text-accent" />
                                        ) : (
                                          <ChevronDown className="h-4 w-4 text-foreground/60" />
                                        )}
                                        <Calendar className="h-4 w-4 text-accent" />
                                        <span className="text-sm font-black uppercase tracking-wider" style={{ fontWeight: '900' }}>
                                          {new Date(date + "T00:00:00").toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}
                                        </span>
                                        {enabledCount > 0 && (
                                          <span className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded-full bg-accent/20 text-accent border border-accent/30">
                                            {enabledCount} of {slots.length} slot{slots.length !== 1 ? 's' : ''} enabled
                                          </span>
                                        )}
                                      </div>
                                      <Button
                                        type="button"
                                        variant="ghost"
                                        size="sm"
                                        onClick={(e) => handleDeselectDay(date, e)}
                                        className="h-7 px-2 text-xs font-bold uppercase tracking-wider text-red-500 hover:text-red-600 hover:bg-red-500/10"
                                      >
                                        <X className="h-3 w-3 mr-1" />
                                        Deselect
                                      </Button>
                                    </div>
                          {isDateExpanded && (
                            <div className="p-4 pt-0 space-y-3">
                              {slots.length > 0 ? (
                                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
                                  {slots.map((slot) => {
                                    const slotStart = new Date(slot.start);
                                    const slotEnd = new Date(slot.end);
                                    const isEnabled = enabledSlotsForDay.has(slot.start);
                                    const timeStr = `${format(slotStart, "HH:mm")} - ${format(slotEnd, "HH:mm")}`;

                                    return (
                                      <button
                                        key={slot.start}
                                        type="button"
                                        onClick={() => onSlotToggle(date, slot.start)}
                                        className={cn(
                                          "p-3 rounded-lg border-2 transition-all text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-2",
                                          isEnabled
                                            ? "border-accent bg-accent text-background"
                                            : "border-foreground/20 bg-foreground/5 text-foreground/60 hover:border-foreground/40"
                                        )}
                                      >
                                        <Clock className="h-3 w-3" />
                                        {timeStr}
                                      </button>
                                    );
                                  })}
                                </div>
                              ) : (
                                <div className="text-sm text-foreground/60 text-center py-4">
                                  No time slots configured for this day
                                </div>
                              )}
                            </div>
                          )}
                                  </div>
                                );
                              })}
                            </div>
                          </div>
                        );
                      })}
                    </CardContent>
                  );
                })()}
              </Card>
            );
          })}
        </div>
      ) : (
        <div className="p-6 rounded-lg border border-foreground/20 bg-foreground/5 text-center">
          <Calendar className="h-8 w-8 mx-auto mb-2 text-foreground/40" />
          <p className="text-sm text-foreground/60">
            No days selected. Select days from the calendar above.
          </p>
        </div>
      )}
    </div>
  );
}

